Numpy --> Low level library written in C for high level maths function

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3, 4])

In [3]:
arr1

array([1, 2, 3, 4])

In [4]:
arr2 = np.array([[1, 2, 3, 4],[1, 2, 3, 4]])

In [5]:
arr2

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [6]:
arr3 = np.ones((3,3))

In [7]:
arr4 = np.arange(10)

In [8]:
arr4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr1

array([1, 2, 3, 4])

In [11]:
arr1.shape

(4,)

In [12]:
arr2.shape

(2, 4)

In [13]:
arr2.ndim

2

In [14]:
arr1.size

4

In [16]:
arr1.itemsize

4

In [18]:
arr7 = np.array([1, 2, 3, 4])

In [19]:
arr8 = np.array([1, 2, 3, 4])

In [20]:
arr7-arr8

array([0, 0, 0, 0])

In [22]:
arr7*arr8

array([ 1,  4,  9, 16])

In [23]:
arr7>arr8

array([False, False, False, False])

In [24]:
arr7.max()

4

In [25]:
arr7.min()

1

In [26]:
arr2


array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [27]:
arr2.transpose()

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])